apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app-v2
  template:
    metadata:
      labels:
        app: django-app-v2
    spec:
      containers:
        - name: django-container
          image: mydjangoapp:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
